package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * FxRateHisId generated by hbm2java
 */
@Embeddable
public class FxRateHisId implements java.io.Serializable {

	private String bssd;
	private String fxId;

	public FxRateHisId() {
	}

	public FxRateHisId(String bssd, String fxId) {
		this.bssd = bssd;
		this.fxId = fxId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "FX_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getFxId() {
		return this.fxId;
	}

	public void setFxId(String fxId) {
		this.fxId = fxId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FxRateHisId))
			return false;
		FxRateHisId castOther = (FxRateHisId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getFxId() == castOther.getFxId()) || (this.getFxId() != null && castOther.getFxId() != null && this
						.getFxId().equals(castOther.getFxId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getFxId() == null ? 0 : this.getFxId().hashCode());
		return result;
	}

}
