package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;

/**
 * HifiveUnderlying generated by hbm2java
 */
@Entity
@Table(name = "HIFIVE_UNDERLYING")
@AnnoNavigationFilter
public class HifiveUnderlying implements java.io.Serializable {

	private HifiveUnderlyingId id;
	private Hifive hifive;
//	private Stock stock;
	private Stock underlying;
	private BigDecimal basePrice;
	private BigDecimal dividend;
	private Character isUphitted;

	public HifiveUnderlying() {
	}

//	public HifiveUnderlying(HifiveUnderlyingId id, Hifive hifive, Stock stock) {
//		this.id = id;
//		this.hifive = hifive;
//		this.stock = stock;
//	}

	public HifiveUnderlying(HifiveUnderlyingId id, Hifive hifive, Stock stock, BigDecimal basePrice,
			BigDecimal dividend, Character isUphitted) {
		this.id = id;
		this.hifive = hifive;
//		this.stock = stock;
		this.underlying =stock;
		this.basePrice = basePrice;
		this.dividend = dividend;
		this.isUphitted = isUphitted;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "underlyingId", column = @Column(name = "STOCK_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public HifiveUnderlyingId getId() {
		return this.id;
	}

	public void setId(HifiveUnderlyingId id) {
		this.id = id;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=11, init=true,type=EColumnType.Entity)
	public Hifive getHifive() {
		return this.hifive;
	}

	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}
	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "STOCK_ID", nullable = false, insertable = false, updatable = false)
//	@AnnoMethodTree(order=20, init=true, type=EColumnType.Entity)
//	public Stock getStock() {
//		return this.stock;
//	}
//
//	public void setStock(Stock stock) {
//		this.stock = stock;
//	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=20, init=true, type=EColumnType.Entity)
	public Stock getUnderlying() {
		return underlying;
	}

	public void setUnderlying(Stock underlying) {
		this.underlying = underlying;
	}

	@Column(name = "BASE_PRICE", precision = 10, scale = 4)
	@AnnoMethodTree(order=30, init=true, align="right", type=EColumnType.Number)
	public BigDecimal getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(BigDecimal basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "DIVIDEND", precision = 10, scale = 4)
	@AnnoMethodTree(order=40, init=true, align ="right", type=EColumnType.Number)
	public BigDecimal getDividend() {
		return this.dividend;
	}

	public void setDividend(BigDecimal dividend) {
		this.dividend = dividend;
	}

	@Column(name = "IS_UPHITTED", length = 1)
	@AnnoMethodTree(order=50, init=true)
	public Character getIsUphitted() {
		return this.isUphitted;
	}

	public void setIsUphitted(Character isUphitted) {
		this.isUphitted = isUphitted;
	}

}
