package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * InterestRate generated by hbm2java
 */
@Entity
@Table(name = "INT_RATE")
public class IntRate implements java.io.Serializable {

	private String irId;
	private MarketVariable marketVariable;
	private String irName;
	private String issueDate;
	private String maturityDate;
	private String compoundMtd;
	private String daycountMtd;
	private String intTerm;
	private BigDecimal couponRate;
	private String sourceTable;
	private String userName;
	private String lastUpdated;
	private BigDecimal versionNo;
//	private IrCurve irCurve;
	private List<IrCurve> irCurves ;
//	private Set<IrCurve> irCurves = new HashSet<IrCurve>(0);
//	private Set<InterateRateHis> interateRateHises = new HashSet<InterateRateHis>(0);

	public IntRate() {
	}

	public IntRate(MarketVariable marketVariable) {
		this.marketVariable = marketVariable;
	}

//	public InterestRate(MarketVariable marketVariable, String irName, String issueDate, String maturityDate,
//			String compoundMtd, String daycountMtd, String intTerm, BigDecimal couponRate, String sourceTable,
//			String userName, String lastUpdated, BigDecimal versionNo, Set<IrCurve> irCurves,
//			Set<InterateRateHis> interateRateHises) {
//		this.marketVariable = marketVariable;
//		this.irName = irName;
//		this.issueDate = issueDate;
//		this.maturityDate = maturityDate;
//		this.compoundMtd = compoundMtd;
//		this.daycountMtd = daycountMtd;
//		this.intTerm = intTerm;
//		this.couponRate = couponRate;
//		this.sourceTable = sourceTable;
//		this.userName = userName;
//		this.lastUpdated = lastUpdated;
//		this.versionNo = versionNo;
//		this.irCurves = irCurves;
//		this.interateRateHises = interateRateHises;
//	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "marketVariable"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IR_ID", unique = true, nullable = false, length = 20)
	@Size(max = 20)
	public String getIrId() {
		return this.irId;
	}

	public void setIrId(String irId) {
		this.irId = irId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	@Size(max = 20)
	public MarketVariable getMarketVariable() {
		return this.marketVariable;
	}

	public void setMarketVariable(MarketVariable marketVariable) {
		this.marketVariable = marketVariable;
	}

	@Column(name = "IR_NAME", length = 50)
	@Size(max = 50)
	public String getIrName() {
		return this.irName;
	}

	public void setIrName(String irName) {
		this.irName = irName;
	}

	@Column(name = "ISSUE_DATE", length = 8)
	@Size(max = 8)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "MATURITY_DATE", length = 8)
	@Size(max = 8)
	public String getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(String maturityDate) {
		this.maturityDate = maturityDate;
	}

	@Column(name = "COMPOUND_MTD", length = 10)
	@Size(max = 10)
	public String getCompoundMtd() {
		return this.compoundMtd;
	}

	public void setCompoundMtd(String compoundMtd) {
		this.compoundMtd = compoundMtd;
	}

	@Column(name = "DAYCOUNT_MTD", length = 10)
	@Size(max = 10)
	public String getDaycountMtd() {
		return this.daycountMtd;
	}

	public void setDaycountMtd(String daycountMtd) {
		this.daycountMtd = daycountMtd;
	}

	@Column(name = "INT_TERM", length = 10)
	@Size(max = 10)
	public String getIntTerm() {
		return this.intTerm;
	}

	public void setIntTerm(String intTerm) {
		this.intTerm = intTerm;
	}

	@Column(name = "COUPON_RATE", precision = 10, scale = 8)
	public BigDecimal getCouponRate() {
		return this.couponRate;
	}

	public void setCouponRate(BigDecimal couponRate) {
		this.couponRate = couponRate;
	}

	@Column(name = "SOURCE_TABLE", length = 50)
	@Size(max = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "USER_NAME", length = 20)
	@Size(max = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LAST_UPDATED", length = 8)
	@Size(max = 8)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "VERSION_NO", precision = 22, scale = 0)
	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	@ManyToMany
	@JoinTable( name="IRC_BUCKET_DETAIL"
		, joinColumns={@JoinColumn(name="IR_ID", referencedColumnName ="IR_ID")} 
	 	, inverseJoinColumns={@JoinColumn(name="IRC_ID", referencedColumnName="IRC_ID")
	 	}
	)
	public List<IrCurve> getIrCurves() {
		return irCurves;
	}

	public void setIrCurves(List<IrCurve> irCurves) {
		this.irCurves = irCurves;
	}



//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "interestRates")
//	public Set<IrCurve> getIrCurves() {
//		return this.irCurves;
//	}
//
//	public void setIrCurves(Set<IrCurve> irCurves) {
//		this.irCurves = irCurves;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interestRate")
//	public Set<InterateRateHis> getInterateRateHises() {
//		return this.interateRateHises;
//	}
//
//	public void setInterateRateHises(Set<InterateRateHis> interateRateHises) {
//		this.interateRateHises = interateRateHises;
//	}

	
}
