package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingUnderlying generated by hbm2java
 */
@Entity
@Table(name = "PRICING_UNDERLYING")
@AnnoNavigationFilter
public class PricingUnderlying implements java.io.Serializable {

	private PricingUnderlyingId id;
	private Pricing pricing;
	private Stock stock;
	private IrCurve irCurve;
	private VolCurve volCurve;

	public PricingUnderlying() {
	}

	public PricingUnderlying(PricingUnderlyingId id, VolCurve volCurve, IrCurve irCurve, Pricing pricing, Stock stock) {
		this.id = id;
		this.volCurve = volCurve;
		this.irCurve = irCurve;
		this.pricing = pricing;
		this.stock = stock;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pricingObject", column = @Column(name = "PRICING_OBJECT", nullable = false, length = 20)),
			@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "underlyingId", column = @Column(name = "STOCK_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public PricingUnderlyingId getId() {
		return this.id;
	}

	public void setId(PricingUnderlyingId id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRICING_OBJECT", referencedColumnName = "PRICING_OBJECT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PROD_ID", referencedColumnName = "PROD_ID", nullable = false, insertable = false, updatable = false) })
	@AnnoMethodTree(order=20, init=true)
	public Pricing getPricing() {
		return this.pricing;
	}

	public void setPricing(Pricing pricing) {
		this.pricing = pricing;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=21, init=true)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}
	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_IRC_ID", nullable = false)
	@AnnoMethodTree(order=30, init=true)
	public IrCurve getIrCurve() {
		return this.irCurve;
	}

	public void setIrCurve(IrCurve irCurve) {
		this.irCurve = irCurve;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOL_CURVE_ID", nullable = false)
	@AnnoMethodTree(order=40, init=true)
	public VolCurve getVolCurve() {
		return this.volCurve;
	}

	public void setVolCurve(VolCurve volCurve) {
		this.volCurve = volCurve;
	}

}
