package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;

/**
 * Pricer generated by hbm2java
 */
@Entity
@Table(name = "PRICER")
@AnnoNavigationFilter
public class Pricer implements java.io.Serializable {

	private String pricerId;
	private String pricerName;
	private String pricerType;
	private String pricerVendor;
	private Long mcNum;
	private Long fdmLatticeNum;
	private String dllName;
	private List<Pricing> pricings = new ArrayList<Pricing>();

	public Pricer() {
	}

	public Pricer(String pricerId) {
		this.pricerId = pricerId;
	}

	public Pricer(String pricerId, String pricerName, String pricerType, String pricerVendor, Long mcNum,
			Long fdmLatticeNum, String dllName, List<Pricing> pricings) {
		this.pricerId = pricerId;
		this.pricerName = pricerName;
		this.pricerType = pricerType;
		this.pricerVendor = pricerVendor;
		this.mcNum = mcNum;
		this.fdmLatticeNum = fdmLatticeNum;
		this.dllName = dllName;
		this.pricings = pricings;
	}

	@Id
	@Column(name = "PRICER_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getPricerId() {
		return this.pricerId;
	}

	public void setPricerId(String pricerId) {
		this.pricerId = pricerId;
	}

	@Column(name = "PRICER_NAME", length = 50)
	@AnnoMethodTree(order=11, init=true)
	public String getPricerName() {
		return this.pricerName;
	}

	public void setPricerName(String pricerName) {
		this.pricerName = pricerName;
	}

	@Column(name = "PRICER_TYPE", length = 10)
	@AnnoMethodTree(order=20, init=true)
	public String getPricerType() {
		return this.pricerType;
	}

	public void setPricerType(String pricerType) {
		this.pricerType = pricerType;
	}

	@Column(name = "PRICER_VENDOR", length = 10)
	@AnnoMethodTree(order=30, init=true)
	public String getPricerVendor() {
		return this.pricerVendor;
	}

	public void setPricerVendor(String pricerVendor) {
		this.pricerVendor = pricerVendor;
	}

	@Column(name = "MC_NUM", precision = 10, scale = 0)
	@AnnoMethodTree(order=40, init=true, align="right")
	public Long getMcNum() {
		return this.mcNum;
	}

	public void setMcNum(Long mcNum) {
		this.mcNum = mcNum;
	}

	@Column(name = "FDM_LATTICE_NUM", precision = 10, scale = 0)
	@AnnoMethodTree(order=41, init=true, align="right")
	public Long getFdmLatticeNum() {
		return this.fdmLatticeNum;
	}

	public void setFdmLatticeNum(Long fdmLatticeNum) {
		this.fdmLatticeNum = fdmLatticeNum;
	}

	@Column(name = "DLL_NAME", length = 50)
	@AnnoMethodTree(order=50, init=true)
	public String getDllName() {
		return this.dllName;
	}

	public void setDllName(String dllName) {
		this.dllName = dllName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricer")
	@AnnoMethodTree(order=60, init=false, type=EColumnType.List)
	public List<Pricing> getPricings() {
		return this.pricings;
	}

	public void setPricings(List<Pricing> pricings) {
		this.pricings = pricings;
	}

}
